In [2]:
import pandas as pd
import os

ot_odr_filename = os.path.join(".", "OT_ODR.csv.bz2")
ot_odr_df = pd.read_csv(ot_odr_filename, compression="bz2", sep=";")
longueur_ot_odr_df = len(ot_odr_df)

equipements_filename = os.path.join(".", 'EQUIPEMENTS.csv')
equipements_df = pd.read_csv(equipements_filename, sep=";")


In [3]:
equipements_df.tail()


EQU_ID MODELE CONSTRUCTEUR MOTEUR
4882  E00271009  MD023         C007  MT021
4883  E00341892  MD063         C007  MT023
4884  E00331551  MD005         C000  MT040
4885  E00373890  MD021         C011  MT0-1
4886  E00365136  MD032         C006  MT016

In [4]:
ot_odr_df.tail()

OT_ID       ODR_ID  \
506553  OT000405952  OM000506539   
506554  OT000405953  OM000506546   
506555  OT000405954  OM000506536   
506556  OT000405955  OM000506545   
506557  OT000405956  OM000506547   

                                              ODR_LIBELLE  \
506553                     REMPLACEMENT D'UN FEU DE RECUL   
506554                    REMPLACEMENT D'UN ECLAIRAGE EXT   
506555               REMPLACEMENT D'UN PASSE SANS CONTACT   
506556         REMPLACEMENT D'UNE LAMPE DE FEU DE GABARIT   
506557  REMPLACEMENT DE LA CASSETTE ENCREUSE D'UN VALI...   

               TYPE_TRAVAIL  DUREE_TRAVAIL              SYSTEM_N1  \
506553          ELECTRICITE           0.04  EQUIPEMENT ELECTRIQUE   
506554            MECANIQUE           0.75  EQUIPEMENT ELECTRIQUE   
506555  EQUIPEMENT EMBARQUE           0.03    EQUIPEMENT EMBARQUE   
506556          ELECTRICITE           0.04  EQUIPEMENT ELECTRIQUE   
506557  EQUIPEMENT EMBARQUE           0.03    EQUIPEMENT EMBARQUE   

                      SYSTEM_N2                    SYSTEM_N3     EQU_ID  \
506553  ECLAIRAGE-SIGNALISATION  ECLAIRAGE-SIGNALISATION EXT  E00040793   
506554  ECLAIRAGE-SIGNALISATION  ECLAIRAGE-SIGNALISATION EXT  E00274690   
506555           TELEBILLETIQUE           PASSE SANS CONTACT  E00256452   
506556  ECLAIRAGE-SIGNALISATION  ECLAIRAGE-SIGNALISATION EXT  E00006122   
506557           TELEBILLETIQUE          VALIDEUR MAGNETIQUE  E00315330   

                    DATE_OT    KILOMETRAGE                 SIG_ORGANE  \
506553  2019-09-30 20:38:09  296005.373397  ECLAIRAGE FEUX EXTERIEURS   
506554  2019-09-30 21:21:20  153050.080050  ECLAIRAGE FEUX EXTERIEURS   
506555  2019-09-30 21:39:29  175063.182439                       AVTT   
506556  2019-09-30 21:55:28  437053.614263  ECLAIRAGE FEUX EXTERIEURS   
506557  2019-09-30 23:43:42   83269.095630                       AVTT   

                   SIG_CONTEXTE            SIG_OBS  LIGNE  
506553  ARRIERE/EXTERIEUR/DROIT              CASSE  L0283  
506554          ARRIERE/LATERAL              CASSE  L0116  
506555              AVANT/PORTE       INTERMITTENT  L0134  
506556      LATERAL/HAUT/GAUCHE  NE FONCTIONNE PAS  L0270  
506557     POSTE CONDUITE/AVANT  NE FONCTIONNE PAS  L0047

In [5]:
ot_odr_df['TYPE_TRAVAIL'].value_counts()

TYPE_TRAVAIL
ELECTRICITE            258129
MECANIQUE              130342
CARROSSERIE             91705
EQUIPEMENT EMBARQUE     19236
MISE AU POINT            5495
STATION SERVICE           726
ROUE                      465
EXTINCTEUR                396
DIVERS                     42
CLIMATISATION              16
BATTERIE                    5
CONTROLE                    1
Name: count, dtype: int64

# Liste déroulante pour SIG_CONTEXTE

In [6]:
import pandas as pd

df = pd.DataFrame(ot_odr_df['SIG_CONTEXTE'])

# Création du dictionnaire
dictionnaire = {}

for _, row in df.iterrows():
    sig_contexte = row['SIG_CONTEXTE']
    contexte_parts = sig_contexte.split('/')
    
    # Parcourir les parties du contexte
    current_dict = dictionnaire
    for part in contexte_parts:
        # Vérifier si la partie existe dans le dictionnaire
        if part not in current_dict:
            current_dict[part] = {}
        
        # Passer au dictionnaire interne
        current_dict = current_dict[part]

print(dictionnaire)
print(dictionnaire['LATERAL']['HAUT'])


{'INTERIEUR': {'GAUCHE': {'ARRIERE': {}, 'AVANT': {}, 'CENTRE': {'CENTRALE': {}}, 'DROIT': {}, 'PLATE FORME': {}, 'LATERAL': {}, 'POSTE CONDUITE': {}, 'HAUT': {}, 'TABLEAU DE BORD': {}, 'PLAFOND': {}, 'BAS': {}, 'PORTE': {}, 'EN VIRAGE': {}, 'EXTERIEUR': {}}, 'POSTE CONDUITE': {'AVANT': {}, 'GAUCHE': {}, 'TABLEAU DE BORD': {}, 'EXTERIEUR': {}, 'HAUT': {}, 'ARRIERE': {}, 'PLAFOND': {}, 'BAS': {}, 'DROIT': {}, "A L'OUVERTURE": {}, 'CENTRE': {'CENTRALE': {}}, 'EN MONTEE': {}, 'PORTE': {}, 'AU FREINAGE': {}, 'AU DEMARRAGE': {}, 'PLATE FORME': {}, 'LATERAL': {}, 'A LA FERMETURE': {}, 'A CHAUD': {}, 'AU POINT MORT': {}, 'DESSOUS': {}, 'EN CHARGE': {}}, 'AVANT': {'ARRIERE': {}, 'POSTE CONDUITE': {}, 'DROIT': {}, 'HAUT': {}, 'GAUCHE': {}, 'PORTE': {}, 'TABLEAU DE BORD': {}, 'PLAFOND': {}, 'A CHAUD': {}, "A L'ACCELERATION": {}, 'BAS': {}, 'CENTRE': {'CENTRALE': {}}, 'EXTERIEUR': {}, 'A LA FERMETURE': {}, 'EN MONTEE': {}, "A L'OUVERTURE": {}, 'PLATE FORME': {}, "A L'ARRET": {}, 'AU FREINAGE': {}

## Stocker la liste dictionnaire

In [7]:
import pickle

path = 'liste_deroulante_SIG_CONTEXTE.pkl'

# Sérialisation du dictionnaire
with open(path,'wb') as fichier:
    pickle.dump(dictionnaire, fichier)

# Désérialisation du dictionnaire
with open(path, 'rb') as fichier:
    dictionnaire = pickle.load(fichier)

# Normaliser le texte

### Supprimer les caractères spéciaux

In [8]:
# import unicodedata

# def Replace_accents(word):
#     try:
#         word = unicodedata.normalize('NFD', word).encode('ascii', 'ignore').decode('utf-8')
#     except:
#         pass
#     return word


# def Delete_special_caractere(word):
#     word = Replace_accents(word)
#     try:
#         word = word.replace('\\', '_').replace('/', '_').replace('-', '_').replace("'", ' ').replace('"', ' ').replace('`', ' ').replace('!', ' ').replace('@', ' ').replace('#', ' ').replace('$', ' ').replace('%', ' ').replace('^', ' ').replace('&', ' ').replace('*', ' ').replace('(', ' ').replace(')', ' ').replace('[', ' ').replace(']', ' ').replace('{', ' ').replace('}', ' ').replace('<', ' ').replace('>', ' ').replace('~', ' ').replace(':', ' ').replace(';', ' ').replace('.', ' ').replace(',', ' ').replace('?', ' ').replace('+', ' ').replace('=', ' ').replace('|', ' ').replace('\\', ' ').replace('\n', ' ').replace('\r', ' ')
#     except:
#         pass
#     return word


In [9]:
ot_odr_df['SIG_ORGANE'].value_counts()

SIG_ORGANE
ECLAIRAGE FEUX EXTERIEURS    189559
CLIGNOTANTS/ DETRESSE         38986
PARE-CHOCS                    33191
RETROVISEUR                   25005
PORTE                         23043
                              ...  
TACHYGRAPHE                       2
LUBRIMATIC                        1
COLMATAGE.F.AIR                   1
PILE BTSAM                        1
ISSUE SEC.                        1
Name: count, Length: 116, dtype: int64

In [10]:
var_cat = ['ODR_LIBELLE', 'TYPE_TRAVAIL',
           'SYSTEM_N1', 'SYSTEM_N2', 'SYSTEM_N3', 
           'SIG_ORGANE', 'SIG_CONTEXTE', 'SIG_OBS', 'LIGNE',
           'SIG_CONTEXTE']
for var in var_cat:
    ot_odr_df[var] = ot_odr_df[var].astype('category')

ot_odr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506558 entries, 0 to 506557
Data columns (total 15 columns):
 #   Column         Non-Null Count   Dtype   
---  ------         --------------   -----   
 0   OT_ID          506558 non-null  object  
 1   ODR_ID         506558 non-null  object  
 2   ODR_LIBELLE    506558 non-null  category
 3   TYPE_TRAVAIL   506558 non-null  category
 4   DUREE_TRAVAIL  506558 non-null  float64 
 5   SYSTEM_N1      506558 non-null  category
 6   SYSTEM_N2      506558 non-null  category
 7   SYSTEM_N3      506558 non-null  category
 8   EQU_ID         506558 non-null  object  
 9   DATE_OT        506558 non-null  object  
 10  KILOMETRAGE    506557 non-null  float64 
 11  SIG_ORGANE     506558 non-null  category
 12  SIG_CONTEXTE   506558 non-null  category
 13  SIG_OBS        506558 non-null  category
 14  LIGNE          506558 non-null  category
dtypes: category(9), float64(2), object(4)
memory usage: 29.7+ MB


### PyAgrum

In [11]:
!pip install pyAgrum
import pyAgrum as gum

rb_projet =  gum.BayesNet("Projet")


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: C:\Users\emgla\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


# Creation du réseau

In [12]:
def Create_noeud(nom_du_noeud, ot_odr_df):
    Nombre_element = ot_odr_df[nom_du_noeud].value_counts()
    va = gum.LabelizedVariable(nom_du_noeud, nom_du_noeud, len(Nombre_element))
    i = 0
    for liste in ot_odr_df[nom_du_noeud].unique():
        # liste = Delete_special_caractere(liste)
        try:
            va.changeLabel(i, str(liste))
        except gum.DuplicateElement as e:
            i -= 1
            print(f"Erreur de duplication dans le noeud '{nom_du_noeud}' pour la valeur : {liste}")
        i += 1
    return va

## Création des noeud

### Création du noeud de SIG_ORGANE

In [13]:
va_SIG_ORGANE = Create_noeud('SIG_ORGANE',ot_odr_df)


### Création du noeud de SIG_OBS

In [14]:
va_SIG_OBS = Create_noeud('SIG_OBS',ot_odr_df)


### Création du noeud de SYSTEM_N1

In [15]:
va_SYSTEM_N1 = Create_noeud('SYSTEM_N1',ot_odr_df)

### Création du noeud de SYSTEM_N2

In [16]:
va_SYSTEM_N2 = Create_noeud('SYSTEM_N2',ot_odr_df)

### Création du noeud de SYSTEM_N3

In [17]:
va_SYSTEM_N3 = Create_noeud('SYSTEM_N3',ot_odr_df)

### Création du noeud de TYPE_TRAVAIL

In [18]:
va_TYPE_TRAVAIL = Create_noeud('TYPE_TRAVAIL',ot_odr_df)

### Création du noeud de ODR_LIBELLE

In [19]:
va_ODR_LIBELLE = Create_noeud('ODR_LIBELLE',ot_odr_df)

### Ajout des noeuds

In [20]:
for va in [va_SIG_ORGANE,va_SYSTEM_N1,va_SYSTEM_N2,va_SYSTEM_N3,va_TYPE_TRAVAIL,va_ODR_LIBELLE,va_SIG_OBS]:
    rb_projet.add(va)

## Création des fixations

In [21]:
rb_projet.addArc("SIG_ORGANE","SYSTEM_N1")
rb_projet.addArc("SIG_OBS","SYSTEM_N1")

rb_projet.addArc("SYSTEM_N1","SYSTEM_N2")
rb_projet.addArc("SYSTEM_N2","SYSTEM_N3")

rb_projet.addArc("SYSTEM_N3","ODR_LIBELLE")
rb_projet.addArc("ODR_LIBELLE","TYPE_TRAVAIL")



# Affichage

In [22]:
# import pyAgrum.lib.ipython as gnb # 

# gnb.showBN(rb_projet)


# Calcul des probabilite

In [23]:
# def Create_Probabilite(df,element,all_element):
#     longueur_df = len(df)
#     count_element = []
#     for liste in all_element:
#         if liste in df[element].unique():
#             count_element.append(len(df.loc[df[element] == liste]) / longueur_df)
#         else: # On met un 0 si le champ n'est pas remplit, si la probabilité n'existe pas
#             count_element.append(0)
#     return count_element

### Calcul des probabilité de SIG_ORGANE

In [24]:
# rb_projet.cpt("SIG_ORGANE")[:] = Create_Probabilite(ot_odr_df,"SIG_ORGANE",ot_odr_df["SIG_ORGANE"].unique())

# rb_projet.cpt("SIG_ORGANE")


### Calcul des probabilité de SIG_OBS

In [25]:
# rb_projet.cpt("SIG_OBS")[:] = Create_Probabilite(ot_odr_df,"SIG_OBS",ot_odr_df["SIG_OBS"].unique())

# rb_projet.cpt("SIG_OBS")

### Calcul des probabilité de SIG_CONTEXTE

In [26]:
# rb_projet.cpt("SIG_CONTEXTE")[:] = Create_Probabilite(ot_odr_df,"SIG_CONTEXTE",ot_odr_df["SIG_CONTEXTE"].unique())
# # Définir la largeur maximale des colonnes

# rb_projet.cpt("SIG_CONTEXTE")

In [27]:
# rb_projet.cpt("SIG_CONTEXTE")[{"SIG_CONTEXTE":'INTERIEUR_GAUCHE_ARRIERE'}]

### Calcul des probabilité de SYSTEM_N1 en fonction de SIG_ORGANE

In [28]:
'''
for liste_SIG in ot_odr_df['SIG_ORGANE'].unique():
    ot_odf_SIG_ORANE = ot_odr_df.loc[ot_odr_df['SIG_ORGANE'] == liste_SIG]
    liste_SIG = Delete_special_caractere(liste_SIG)

    rb_projet.cpt("SYSTEM_N1")[{"SIG_ORGANE":liste_SIG}] = Create_Probabilite(ot_odf_SIG_ORANE,"SYSTEM_N1",ot_odr_df["SYSTEM_N1"].unique())

rb_projet.cpt("SYSTEM_N1")
'''

'\nfor liste_SIG in ot_odr_df[\'SIG_ORGANE\'].unique():\n    ot_odf_SIG_ORANE = ot_odr_df.loc[ot_odr_df[\'SIG_ORGANE\'] == liste_SIG]\n    liste_SIG = Delete_special_caractere(liste_SIG)\n\n    rb_projet.cpt("SYSTEM_N1")[{"SIG_ORGANE":liste_SIG}] = Create_Probabilite(ot_odf_SIG_ORANE,"SYSTEM_N1",ot_odr_df["SYSTEM_N1"].unique())\n\nrb_projet.cpt("SYSTEM_N1")\n'

### Calcul des probabilité de SYSTEM_N1 en fonction de SIG_ORGANE et SIG_OBS

In [29]:
# for sig_organe in ot_odr_df['SIG_ORGANE'].unique():
#     ot_odf_sig_organe = ot_odr_df.loc[ot_odr_df['SIG_ORGANE'] == sig_organe]
#     sig_organe = Delete_special_caractere(sig_organe)
    
#     for sig_obs in ot_odr_df['SIG_OBS'].unique():
#         ot_odf_sig_obs = ot_odf_sig_organe.loc[ot_odf_sig_organe['SIG_OBS'] == sig_obs]
#         sig_obs = Delete_special_caractere(sig_obs)

#         rb_projet.cpt("SYSTEM_N1")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}] = Create_Probabilite(ot_odf_sig_obs, "SYSTEM_N1", ot_odr_df["SYSTEM_N1"].unique())

# print(rb_projet.cpt("SYSTEM_N1"))


### Calcul des probabilité de SYSTEM_N2 en fonction de SYSTEM_N1

In [30]:
# for liste_N1 in ot_odr_df['SYSTEM_N1'].unique():
#     ot_odf_SYSTEM_N1 = ot_odr_df.loc[ot_odr_df['SYSTEM_N1'] == liste_N1]
#     liste_N1 = Delete_special_caractere(liste_N1)

#     rb_projet.cpt("SYSTEM_N2")[{"SYSTEM_N1":liste_N1}] = Create_Probabilite(ot_odf_SYSTEM_N1,"SYSTEM_N2",ot_odr_df["SYSTEM_N2"].unique())
# rb_projet.cpt("SYSTEM_N2")

### Calcul des probabilité de SYSTEM_N3 en fonction de SYSTEM_N2

In [31]:
# for liste_N2 in ot_odr_df['SYSTEM_N2'].unique():
#     ot_odf_SYSTEM_N2 = ot_odr_df.loc[ot_odr_df['SYSTEM_N2'] == liste_N2]
#     liste_N2 = Delete_special_caractere(liste_N2)
#     rb_projet.cpt("SYSTEM_N3")[{"SYSTEM_N2":liste_N2}] = Create_Probabilite(ot_odf_SYSTEM_N2,"SYSTEM_N3",ot_odr_df["SYSTEM_N3"].unique())
# rb_projet.cpt("SYSTEM_N3")

# Affichage

### Affichage Tableau

In [32]:
# def afficher_probabilites_tableau(sig_organe,sig_obs,rb_projet):
#     # Définir la valeur choisie pour SIG_ORGANE
#     rb_projet.cpt("SIG_ORGANE")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}] = 1.0
#     colonnes = ot_odr_df['SYSTEM_N1'].unique()
#     # Calculer la probabilité conditionnelle pour SYSTEM_N1
#     proba_system_n1 = rb_projet.cpt("SYSTEM_N1")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}]
#     # Déterminer la longueur maximale des noms de colonnes
#     longueur_max = max(len(colonne) for colonne in colonnes)

#     # Afficher l'en-tête du tableau
#     print(f"| {'Variable':<{longueur_max}} | Probabilité |")
#     print(f"+{'-' * (longueur_max + 2)}+-------------+")

#     # Afficher les lignes du tableau avec les noms de colonnes et les probabilités
#     for colonne, probabilite in zip(colonnes, proba_system_n1):
#         print(f"| {colonne:<{longueur_max}} | {probabilite:.4f}      |")

#     # Afficher la ligne de séparation du tableau
#     print(f"+{'-' * (longueur_max + 2)}+-------------+")

# sig_organe_choisi = "ECLAIRAGE FEUX EXTERIEURS"
# # sig_obs_choisi = "CASSE"
# sig_obs_choisi = "NE FONCTIONNE PAS"

# afficher_probabilites_tableau(sig_organe_choisi,sig_obs_choisi,rb_projet)

In [33]:
# import matplotlib.pyplot as plt

# def afficher_probabilites(sig_organe,sig_obs,rb_projet):
#     # Définir la valeur choisie pour SIG_ORGANE
#     rb_projet.cpt("SIG_ORGANE")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}] = 1.0
#     colonne = ot_odr_df['SYSTEM_N1'].unique()
#     # Calculer la probabilité conditionnelle pour SYSTEM_N1
#     proba_system_n1 = rb_projet.cpt("SYSTEM_N1")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}]

#     # Afficher la probabilité pour SYSTEM_N1 avec une taille de figure plus grande
#     plt.figure(figsize=(40, 20))
#     plt.bar(colonne, proba_system_n1, color='blue')
#     plt.title(str("Probabilité la plus probable pour SYSTEM_N1 en ayant " + sig_organe_choisi + " " + sig_obs))
#     plt.xlabel("SYSTEM_N1")
#     plt.ylabel("Probabilité")
#     plt.show()
    

# sig_organe_choisi = "ECLAIRAGE FEUX EXTERIEURS"
# sig_obs_choisi = "CASSE"
# afficher_probabilites(sig_organe_choisi,sig_obs_choisi,rb_projet)


In [34]:
import pyagrum_extra
rb_projet.fit_bis(ot_odr_df, verbose_mode=True)

- Learn CPT TYPE_TRAVAIL
- Learn CPT SIG_ORGANE
- Learn CPT SYSTEM_N3
- Learn CPT ODR_LIBELLE
- Learn CPT SYSTEM_N2
- Learn CPT SIG_OBS
- Learn CPT SYSTEM_N1


In [35]:
rb_projet.cpt("SIG_OBS")

(pyAgrum.Potential<double>@0000024B79566FE0) 
  SIG_OBS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
DEBOITE  |ABSENT   |VIBRE    |CASSE    |BLOQUE   |ENFONCE  |DESSERRE |RAYE     |LACERE   |INTERRUPT|MANQUE   |ODEUR    |CLAQUE   |FERME MAL|FONCTIONN|VOYANT AL|ARRACHE  |NE FONCTI|INSUFFISA|FUITE    |DUR      |FUME/CHAU|ASPIRER  |BRUYANT  |DEGONFLE |VOYANT HS|JEU      |TAGUE    |BRUTAL   |USE/VIDE |INTERMITT|CLIGNOTE |BLESSE   |INCOMPLET|CALE     |FAUX CONT|BAL

In [36]:
rb_projet.cpt("SYSTEM_N1")

(pyAgrum.Potential<double>@0000024B6B5FEA20) 
             ||  SYSTEM_N1                                                                                        |
SIG_OR|SIG_OB||EQUIPEMEN|EQUIPEMEN|EQUIPEMEN|EQUIPEMEN|EQUIPEMEN|EQUIPEMEN|EQUIPEMEN|EQUIPEMEN|EQUIPEMEN|DIVERS   |
------|------||---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|
GLACE/|DEBOIT|| 0.0059  | 0.0059  | 0.0059  | 0.0059  | 0.4765  | 0.2412  | 0.0059  | 0.2412  | 0.0059  | 0.0059  |
KLAXON|DEBOIT|| 0.0000  | 0.0000  | 0.0000  | 0.0857  | 0.0857  | 0.3429  | 0.3143  | 0.1714  | 0.0000  | 0.0000  |
VOITUR|DEBOIT|| 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  |
PARE-C|DEBOIT|| 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  |
SECURI|DEBOIT|| 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  | 0.1000  |
VOLANT|DEBOIT|| 0.1000  | 

In [37]:
pred_prob = rb_projet.predict_proba(ot_odr_df[["SIG_OBS"]].iloc[-1000:], var_target="SYSTEM_N1", show_progress=True)
print("Probabilité des prédictions : ")
print(pred_prob)

pred = rb_projet.predict(ot_odr_df[["SIG_OBS"]].iloc[-1000:], var_target="SYSTEM_N1", show_progress=True)
print("Prédictions : ")
print(pred)

Probabilité des prédictions : 
[[0.09999636 0.09999833 0.09999636 ... 0.09999636 0.09999735 0.09999833]
 [0.09999636 0.09999833 0.09999636 ... 0.09999636 0.09999735 0.09999833]
 [0.01899087 0.02098219 0.04171386 ... 0.562789   0.05532886 0.02034254]
 ...
 [0.03000365 0.03276084 0.03308767 ... 0.53110356 0.03526412 0.03000365]
 [0.09999636 0.09999833 0.09999636 ... 0.09999636 0.09999735 0.09999833]
 [0.09999636 0.09999833 0.09999636 ... 0.09999636 0.09999735 0.09999833]]
Prédictions : ss: 100%
['EQUIPEMENT CLIMATIQUE' 'EQUIPEMENT CLIMATIQUE'
 'EQUIPEMENT DE TRANSMISSION' 'EQUIPEMENT CLIMATIQUE'
 'EQUIPEMENT DE TRANSMISSION' 'EQUIPEMENT DE TRANSMISSION'
 'EQUIPEMENT DE TRANSMISSION' 'EQUIPEMENT DE TRANSMISSION'
 'EQUIPEMENT CLIMATIQUE' 'EQUIPEMENT ELECTRIQUE' 'EQUIPEMENT EMBARQUE'
 'EQUIPEMENT EMBARQUE' 'EQUIPEMENT EMBARQUE' 'EQUIPEMENT CLIMATIQUE'
 'EQUIPEMENT CLIMATIQUE' 'EQUIPEMENT EMBARQUE' 'EQUIPEMENT EMBARQUE'
 'EQUIPEMENT DE TRANSMISSION' 'EQUIPEMENT EMBARQUE'
 'EQUIPEMENT ELECTRI

In [38]:
print(rb_projet.cpt("TYPE_TRAVAIL"))


      ||  TYPE_TRAVAIL                                                                                                         |
ODR_LI||CARROSSER|ELECTRICI|MECANIQUE|MISE AU P|EQUIPEMEN|EXTINCTEU|STATION S|ROUE     |CLIMATISA|BATTERIE |DIVERS   |CONTROLE |
------||---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|---------|
REMPLA|| 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.9817  | 0.0017  | 0.0017  |
REMPLA|| 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.0017  | 0.9817  | 0.0017  | 0.0017  | 0.0017  |
REMPLA|| 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.5417  | 0.0417  | 0.0417  | 0.0417  |
REMPLA|| 0.0032  | 0.0032  | 0.0032  | 0.0032  | 0.0032  | 0.0032  | 0.0032  | 0.0032  | 0.9647  | 0.0032  | 0.0032  | 0.0032  |
REMPLA|| 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.0417  | 0.5417 

In [39]:
print(rb_projet.cpt("ODR_LIBELLE"))


      ||  ODR_LIBELLE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

In [52]:
print(rb_projet.cpt("SYSTEM_N2"))


      ||  SYSTEM_N2                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
SYSTEM||VITRAGE  |ECLAIRAGE|EQUIPEMEN|ELEMENT C|PORTE    |INFORMATI|VENTILATI|LIAISON A|FREIN D'E|ACCESSOIR|MOTEUR TH|DEPOLLUTI|CHASSIS  |FREIN PRI|BOITE DE |ARTICULAT|CIRCUIT D|TRANSMISS|CLIMATISA|CIRCUIT D|AMENAGEME|CIRCUIT D|CIRCUIT D|REFROIDIS|CIRCUIT D|CIRCUIT D|CIRCUIT D|CHAUFFAGE|CIRCUIT D|FREIN DE |-        |POSTE DE |ACCESSIBI|INDICATEU|CIRCUIT D|AIDE A L'|STOCKAGE |CIRCUIT D|SECURITE |TELEBILLE|MAINTENAN|ENERGIE T|MOTEUR EL|CIRCUIT D|FREIN SEC|
------||---------|---------|---------|---------|---------|---------|---------|---

In [73]:
import numpy as np

def afficher_probabilites_tableau(sig_organe, sig_obs, rb_projet):
    dictionnaire = {}
    colonnes = ot_odr_df['SYSTEM_N1'].unique()
    colonnes2 = ot_odr_df['SYSTEM_N2'].unique()
    colonnes3 = ot_odr_df['SYSTEM_N3'].unique()
    colonnes4 = ot_odr_df['ODR_LIBELLE'].unique()
    colonnes5 = ot_odr_df['TYPE_TRAVAIL'].unique()

    # Calculer la probabilité conditionnelle pour SYSTEM_N1
    proba_system_n1 = rb_projet.cpt("SYSTEM_N1")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}]

    # Définir la valeur choisie pour SIG_ORGANE
    rb_projet.cpt("SIG_ORGANE")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}] = 1.0

    # Calculer les probabilités pour SYSTEM_N2
    proba_system_n2 = np.dot(proba_system_n1, rb_projet.cpt("SYSTEM_N2")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}])

    # Calculer les probabilités pour SYSTEM_N3
    proba_system_n3 = np.dot(proba_system_n2, rb_projet.cpt("SYSTEM_N3")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}])

    # Calculer les probabilités pour ODR_LIBELLE
    proba_system_lib = np.dot(proba_system_n3, rb_projet.cpt("ODR_LIBELLE")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}])

    # Calculer les probabilités pour TYPE_TRAVAIL
    proba_system_tra = np.dot(proba_system_lib, rb_projet.cpt("TYPE_TRAVAIL")[{"SIG_ORGANE": sig_organe, "SIG_OBS": sig_obs}])

    # Créer un dictionnaire avec l'association nom de colonne et probabilité
    dictionnaire = {
        'SYSTEM_N1': dict(zip(colonnes, proba_system_n1)),
        'SYSTEM_N2': dict(zip(colonnes2, proba_system_n2)),
        'SYSTEM_N3': dict(zip(colonnes3, proba_system_n3)),
        'ODR_LIBELLE': dict(zip(colonnes4, proba_system_lib)),
        'TYPE_TRAVAIL': dict(zip(colonnes5, proba_system_tra))
    }

    return dictionnaire

sig_organe_choisi = "ECLAIRAGE FEUX EXTERIEURS"
sig_obs_choisi = "CASSE"
# sig_obs_choisi = "NE FONCTIONNE PAS"

sss = afficher_probabilites_tableau(sig_organe_choisi, sig_obs_choisi, rb_projet)
sss['SYSTEM_N2']



{'VITRAGE': 0.002933065723711881,
 'ECLAIRAGE-SIGNALISATION': 0.004992511233150275,
 'EQUIPEMENT DE DIRECTION': 0.013917641045300619,
 'ELEMENT CARROSSERIE EXT': 0.1118885041213481,
 'PORTE': 0.0027019040316912657,
 'INFORMATION VOYAGEUR': 0.0005398152770843735,
 'VENTILATION': 0.04484386347131445,
 'LIAISON AU SOL': 0.0021467798302546182,
 "FREIN D'EXPLOITATION": 0.04541593438781488,
 'ACCESSOIRE DE VISIBILITE': 0.004110701430954262,
 'MOTEUR THERMIQUE': 8.998332016504259e-05,
 'DEPOLLUTION': 0.0028948292511631994,
 'CHASSIS': 0.003908787639364411,
 'FREIN PRINCIPAL': 0.0002719486381541136,
 'BOITE DE VITESSES': 0.00026581577582460717,
 'ARTICULATION CLE': 0.00082057697968796,
 'CIRCUIT DE LUBRIFICATION': 0.0034852076200509174,
 'TRANSMISSION': 0.002027916776402423,
 'CLIMATISATION': 0.048618840433066884,
 'CIRCUIT DE DEMARRAGE': 8.761231899294897e-06,
 'AMENAGEMENT INT': 0.00029657293497363795,
 "CIRCUIT D'ECHAPPEMENT": 0.010497322447546309,
 'CIRCUIT DE GESTION MOTEUR': 0.0458999186